# Generated by Django 4.2 on 2024-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
