# Generated by Django 4.2 on 2024-04-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0003_alter_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='secondary_image/'),
        ),
    ]
