# Generated by Django 4.2 on 2024-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0004_title_secondary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='quoatation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
