# Generated by Django 4.2 on 2024-04-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0008_alter_contactus_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('faculty', models.CharField(max_length=100)),
                ('pass_out_year', models.CharField(max_length=4)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apply_for_country', models.CharField(max_length=100)),
                ('english_proficiency_test', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=10)),
                ('remarks', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
