# Generated by Django 4.2 on 2024-04-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0009_applyasstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAsAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=100)),
                ('consultancy_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
