# Generated by Django 4.2 on 2024-04-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0011_applyasagent_create_date_applyasstudent_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
