# Generated by Django 4.2.9 on 2024-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0012_title_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
