# Generated by Django 4.2.9 on 2024-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0013_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
