# Generated by Django 4.2.9 on 2024-04-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0015_subcategory_title_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admindash.subcategory', verbose_name='Select Download Category'),
        ),
    ]
