# Generated by Django 4.2.9 on 2024-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0016_title_link_alter_title_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyasagent',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applyasagent',
            name='consultancy_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyasagent',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyasagent',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyasagent',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='applyasagent',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applyasagent',
            name='years_of_experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='apply_for_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='english_proficiency_test',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='faculty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='pass_out_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applyasstudent',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
