# Generated by Django 4.2.9 on 2024-04-22 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0018_alter_applyasagent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyasagent',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 22, 12, 22, 6, 976013, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
