# Generated by Django 4.2.9 on 2024-04-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0019_alter_applyasagent_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyasagent',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
