# Generated by Django 4.2 on 2024-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0020_rename_create_date_applyasagent_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
